apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-project-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking-project-v1
  template:
    metadata:
      labels:
        app: banking-project-v1
    spec:
      containers:
        - name: banking-project-v1
          image: suvo7886/banking-project:1.0
          ports:
            - containerPort: 8080
---           
apiVersion: v1
kind: Service
metadata:
  name: insurance-project-v1
spec:
  type: NodePort
  selector:
    app: banking-project-v1
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
