apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-project-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcare-project-v1
  template:
    metadata:
      labels:
        app: healthcare-project-v1
    spec:
      containers:
        - name: healthcare-project-v1
          image: suvo7886/healthcare-project:1.0
          ports:
            - containerPort: 8082
---           
apiVersion: v1
kind: Service
metadata:
  name: healthcare-project-v1
spec:
  type: NodePort
  selector:
    app: healthcare-project-v1
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
